site_name: Your Advanced Electrode Localizer Viewer for Python
site_url: https://dipterix.org/threebrainpy/
repo_url: https://github.com/dipterix/threebrainpy
repo_name: GitHub


theme:
  name: "material"
  logo: assets/images/favicon.png

plugins:
  - mkdocstrings
  - search

markdown_extensions:
  - attr_list

nav:
  - Home: index.md
  - "Getting Started": getting-started.md
  - "API Reference": 
    - "<code>threebrainpy.core</code>": 
      - "<code>&lt;Class Brain&gt;</code>": api-core-brain.md
      - "<code>&lt;Class Vec3&gt;</code>": api-core-vec3.md
      - "<code>&lt;Class Mat44&gt;</code>": api-core-mat44.md
    - "Module utils": api-utils.md
