[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.urls]
"Homepage" = "https://github.com/dipterix/threeBrainPy/"
"Bug Tracker" = "https://github.com/dipterix/threeBrainPy/issues"
"Documentation" = "https://dipterix.org/threeBrainPy/"
